--
-- PostgreSQL database dump
--

-- Dumped from database version 15.12 (Debian 15.12-1.pgdg120+1)
-- Dumped by pg_dump version 15.12 (Debian 15.12-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Devices" (
    "Id" integer NOT NULL,
    "Status" integer NOT NULL,
    "Metadata" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "DeviceName" character varying(100) DEFAULT ''::character varying NOT NULL,
    "Manufacturer" character varying(100) DEFAULT ''::character varying NOT NULL,
    "Model" character varying(100) DEFAULT ''::character varying NOT NULL,
    "PictureUrl" text DEFAULT ''::text NOT NULL,
    "Version" character varying(50) DEFAULT ''::character varying NOT NULL,
    "GroupId" uuid
);


ALTER TABLE public."Devices" OWNER TO postgres;

--
-- Name: Devices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Devices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Devices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Groups" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "IndustryCategoryId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Groups" OWNER TO postgres;

--
-- Name: IndustryCategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IndustryCategories" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."IndustryCategories" OWNER TO postgres;

--
-- Name: Mesures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Mesures" (
    "Id" integer NOT NULL,
    "Value" double precision NOT NULL,
    "AlertedMesure" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SensorLocalId" integer,
    "SensorDeviceId" integer
);


ALTER TABLE public."Mesures" OWNER TO postgres;

--
-- Name: Mesures_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Mesures" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Mesures_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sensors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sensors" (
    "LocalId" integer NOT NULL,
    "Type" integer NOT NULL,
    "MinValue" double precision NOT NULL,
    "MaxValue" double precision NOT NULL,
    "AlertEnabled" boolean NOT NULL,
    "Metadata" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "DeviceId" integer NOT NULL
);


ALTER TABLE public."Sensors" OWNER TO postgres;

--
-- Name: UserGroups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserGroups" (
    "UserId" uuid NOT NULL,
    "GroupId" uuid NOT NULL,
    "Role" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserId1" uuid
);


ALTER TABLE public."UserGroups" OWNER TO postgres;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Username" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "DateOfBirth" timestamp with time zone,
    "Address" character varying(500),
    "Email" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Devices" ("Id", "Status", "Metadata", "CreatedAt", "UpdatedAt", "DeviceName", "Manufacturer", "Model", "PictureUrl", "Version", "GroupId") FROM stdin;
1	1	"{}"	2025-10-22 13:46:08.951797+00	2025-10-23 22:03:19.354503+00	string					\N
\.


--
-- Data for Name: Groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Groups" ("Id", "Name", "Description", "IndustryCategoryId", "CreatedAt", "UpdatedAt") FROM stdin;
f6e63612-5c1a-4747-acfc-445f02a0222d	string	string	d6dbfb22-4959-4385-acbf-257b5ceb5f95	2025-10-22 14:14:58.601919+00	2025-10-22 14:14:58.601943+00
0ed76987-20df-4523-9e0c-0c739487bf61	Updated	str00ing	95ffcb0f-7330-48e7-bfc2-f4ca69188ead	2025-10-21 22:26:30.16113+00	2025-10-22 14:48:05.10568+00
8e94ee3f-404b-4401-8fb9-7b92b4271359	Ciao	Ciao oooooosasasas	d6dbfb22-4959-4385-acbf-257b5ceb5f95	2025-10-22 13:46:08.951797+00	2025-10-23 22:03:19.226799+00
\.


--
-- Data for Name: IndustryCategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."IndustryCategories" ("Id", "Name", "Description", "CreatedAt", "UpdatedAt") FROM stdin;
95ffcb0f-7330-48e7-bfc2-f4ca69188ead	Capteur de feu	Capter de feu mich normal	2025-10-21 22:25:19.515845+00	2025-10-21 22:25:19.51587+00
d6dbfb22-4959-4385-acbf-257b5ceb5f95	string	string	2025-10-22 12:59:29.325822+00	2025-10-22 12:59:29.325848+00
\.


--
-- Data for Name: Mesures; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Mesures" ("Id", "Value", "AlertedMesure", "CreatedAt", "SensorLocalId", "SensorDeviceId") FROM stdin;
1	50	t	2025-10-22 21:35:32.136387+00	1	1
2	50	t	2025-10-22 21:35:34.813998+00	1	1
3	50	t	2025-10-22 21:35:48.493353+00	1	1
\.


--
-- Data for Name: Sensors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sensors" ("LocalId", "Type", "MinValue", "MaxValue", "AlertEnabled", "Metadata", "CreatedAt", "UpdatedAt", "DeviceId") FROM stdin;
1	2	0	100	t	"{}"	2025-10-22 13:46:08.951797+00	2025-10-22 13:46:08.951797+00	1
\.


--
-- Data for Name: UserGroups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserGroups" ("UserId", "GroupId", "Role", "Status", "CreatedAt", "UpdatedAt", "UserId1") FROM stdin;
f34ac52a-0c0c-4bd2-9f87-54dc8340ec24	f6e63612-5c1a-4747-acfc-445f02a0222d	0	0	2025-10-22 16:08:15.903206+00	2025-10-22 16:08:15.903277+00	\N
f34ac52a-0c0c-4bd2-9f87-54dc8340ec24	8e94ee3f-404b-4401-8fb9-7b92b4271359	1	2	2025-10-22 16:12:08.906085+00	2025-10-22 16:12:08.906085+00	\N
f34ac52a-0c0c-4bd2-9f87-54dc8340ec24	0ed76987-20df-4523-9e0c-0c739487bf61	0	0	2025-10-22 16:53:10.265794+00	2025-10-22 16:53:10.265858+00	\N
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Name", "LastName", "Username", "PasswordHash", "CreatedAt", "UpdatedAt", "DateOfBirth", "Address", "Email") FROM stdin;
f34ac52a-0c0c-4bd2-9f87-54dc8340ec24	Helmi	Ba	helmi	$2a$11$O7HeH7kIrvuR1dS7ghE1O.FL1CHuL.C7U1t8k8co4Kn06FqG8h61S	2025-10-20 14:19:41.641953+00	2025-10-20 14:19:41.641978+00	2005-10-20 14:19:21.81+00	La capitale ♥	\N
c029749e-8f8b-4df1-933e-199df6739eef	string	string	string	$2a$11$bRKVtzglU5hPYpeJ2oooceI.76bjEBB4ML7zCUy5VeLXqyp/ZjmYe	2025-10-20 16:03:15.846029+00	2025-10-20 16:03:15.846054+00	2025-10-20 16:03:13.292+00	string	\N
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251019234707_InitialCreate	9.0.10
20251021220838_Fix_IndustryCategoryId_Type	9.0.10
20251022210557_CreateDevice	9.0.10
20251022214659_PendingSensorDeviceAddDB	9.0.10
20251023204407_FixUserGroup_AddDeviceAttibutes	9.0.10
20251023213709_FixGroup_Device	9.0.10
\.


--
-- Name: Devices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Devices_Id_seq"', 1, false);


--
-- Name: Mesures_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Mesures_Id_seq"', 3, true);


--
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY ("Id");


--
-- Name: Groups PK_Groups; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "PK_Groups" PRIMARY KEY ("Id");


--
-- Name: IndustryCategories PK_IndustryCategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IndustryCategories"
    ADD CONSTRAINT "PK_IndustryCategories" PRIMARY KEY ("Id");


--
-- Name: Mesures PK_Mesures; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Mesures"
    ADD CONSTRAINT "PK_Mesures" PRIMARY KEY ("Id");


--
-- Name: Sensors PK_Sensors; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensors"
    ADD CONSTRAINT "PK_Sensors" PRIMARY KEY ("DeviceId", "LocalId");


--
-- Name: UserGroups PK_UserGroups; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserGroups"
    ADD CONSTRAINT "PK_UserGroups" PRIMARY KEY ("UserId", "GroupId");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Devices_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Devices_GroupId" ON public."Devices" USING btree ("GroupId");


--
-- Name: IX_Groups_IndustryCategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Groups_IndustryCategoryId" ON public."Groups" USING btree ("IndustryCategoryId");


--
-- Name: IX_Mesures_SensorDeviceId_SensorLocalId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Mesures_SensorDeviceId_SensorLocalId" ON public."Mesures" USING btree ("SensorDeviceId", "SensorLocalId");


--
-- Name: IX_UserGroups_GroupId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserGroups_GroupId" ON public."UserGroups" USING btree ("GroupId");


--
-- Name: IX_UserGroups_UserId1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserGroups_UserId1" ON public."UserGroups" USING btree ("UserId1");


--
-- Name: IX_Users_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Username" ON public."Users" USING btree ("Username");


--
-- Name: Devices FK_Devices_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "FK_Devices_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE SET NULL;


--
-- Name: Groups FK_Groups_IndustryCategories_IndustryCategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "FK_Groups_IndustryCategories_IndustryCategoryId" FOREIGN KEY ("IndustryCategoryId") REFERENCES public."IndustryCategories"("Id") ON DELETE SET NULL;


--
-- Name: Mesures FK_Mesures_Sensors_SensorDeviceId_SensorLocalId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Mesures"
    ADD CONSTRAINT "FK_Mesures_Sensors_SensorDeviceId_SensorLocalId" FOREIGN KEY ("SensorDeviceId", "SensorLocalId") REFERENCES public."Sensors"("DeviceId", "LocalId") ON DELETE CASCADE;


--
-- Name: Sensors FK_Sensors_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensors"
    ADD CONSTRAINT "FK_Sensors_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: UserGroups FK_UserGroups_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserGroups"
    ADD CONSTRAINT "FK_UserGroups_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: UserGroups FK_UserGroups_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserGroups"
    ADD CONSTRAINT "FK_UserGroups_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: UserGroups FK_UserGroups_Users_UserId1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserGroups"
    ADD CONSTRAINT "FK_UserGroups_Users_UserId1" FOREIGN KEY ("UserId1") REFERENCES public."Users"("Id");


--
-- PostgreSQL database dump complete
--

